---
- name: Provision k8s-pnode
  hosts: k8s-all-nodes
  remote_user: root
  tasks:
    - include: ../../../roles/k8s-prete-gluster/tasks/clean-slate.yml wp_user=root
    - name: Add the hostname
      command: hostnamectl set-hostname {{inventory_hostname}}
